-- Study plans table
CREATE TABLE IF NOT EXISTS public.study_plans (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    goal TEXT NOT NULL,
    available_hours_per_day NUMERIC(4,2) NOT NULL CHECK (available_hours_per_day > 0),
    deadline DATE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.study_plans IS 'User study plans generated by AI';

ALTER TABLE public.study_plans ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own study plans" ON public.study_plans
    FOR SELECT USING (owner_id = auth.uid());

CREATE POLICY "Users can insert own study plans" ON public.study_plans
    FOR INSERT WITH CHECK (owner_id = auth.uid());

CREATE POLICY "Users can update own study plans" ON public.study_plans
    FOR UPDATE USING (owner_id = auth.uid());

CREATE POLICY "Users can delete own study plans" ON public.study_plans
    FOR DELETE USING (owner_id = auth.uid());

CREATE INDEX idx_study_plans_owner_id ON public.study_plans(owner_id);

-- Study tasks table
CREATE TABLE IF NOT EXISTS public.study_tasks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    plan_id UUID NOT NULL REFERENCES public.study_plans(id) ON DELETE CASCADE,
    owner_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    scheduled_date DATE NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT false,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.study_tasks IS 'Daily tasks within a study plan';

ALTER TABLE public.study_tasks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own study tasks" ON public.study_tasks
    FOR SELECT USING (owner_id = auth.uid());

CREATE POLICY "Users can insert own study tasks" ON public.study_tasks
    FOR INSERT WITH CHECK (owner_id = auth.uid());

CREATE POLICY "Users can update own study tasks" ON public.study_tasks
    FOR UPDATE USING (owner_id = auth.uid());

CREATE POLICY "Users can delete own study tasks" ON public.study_tasks
    FOR DELETE USING (owner_id = auth.uid());

CREATE INDEX idx_study_tasks_plan_id ON public.study_tasks(plan_id);
CREATE INDEX idx_study_tasks_owner_id ON public.study_tasks(owner_id);
CREATE INDEX idx_study_tasks_scheduled_date ON public.study_tasks(scheduled_date);
